basePath: /
definitions:
  rmbproxy.Message:
    properties:
      cmd:
        example: zos.statistics.get
        type: string
      dat:
        example: ""
        type: string
      dst:
        example:
        - 2
        - 3
        items:
          type: integer
        type: array
      err:
        example: ""
        type: string
      exp:
        example: 0
        type: integer
      now:
        example: 1631078674
        type: integer
      ret:
        example: ""
        type: string
      shm:
        example: ""
        type: string
      src:
        example: 1
        type: integer
      try:
        example: 2
        type: integer
      uid:
        example: ""
        type: string
      ver:
        example: 1
        type: integer
    type: object
  rmbproxy.MessageIdentifier:
    properties:
      retqueue:
        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        type: string
    type: object
  types.Capacity:
    properties:
      cru:
        type: integer
      hru:
        type: integer
      mru:
        type: integer
      sru:
        type: integer
    type: object
  types.CapacityResult:
    properties:
      total_resources:
        $ref: '#/definitions/types.Capacity'
      used_resources:
        $ref: '#/definitions/types.Capacity'
    type: object
  types.Contract:
    properties:
      billing:
        items:
          $ref: '#/definitions/types.ContractBilling'
        type: array
      contractId:
        type: integer
      created_at:
        type: integer
      details: {}
      state:
        type: string
      twinId:
        type: integer
      type:
        type: string
    type: object
  types.ContractBilling:
    properties:
      amountBilled:
        type: integer
      discountReceived:
        type: string
      timestamp:
        type: integer
    type: object
  types.Counters:
    properties:
      accessNodes:
        type: integer
      contracts:
        type: integer
      countries:
        type: integer
      farms:
        type: integer
      gateways:
        type: integer
      nodes:
        type: integer
      nodesDistribution:
        additionalProperties:
          type: integer
        type: object
      publicIps:
        type: integer
      totalCru:
        type: integer
      totalHru:
        type: integer
      totalMru:
        type: integer
      totalSru:
        type: integer
      twins:
        type: integer
    type: object
  types.Farm:
    properties:
      certificationType:
        type: string
      dedicated:
        type: boolean
      farmId:
        type: integer
      name:
        type: string
      pricingPolicyId:
        type: integer
      publicIps:
        items:
          $ref: '#/definitions/types.PublicIP'
        type: array
      stellarAddress:
        type: string
      twinId:
        type: integer
    type: object
  types.Location:
    properties:
      city:
        type: string
      country:
        type: string
    type: object
  types.Node:
    properties:
      certificationType:
        type: string
      city:
        type: string
      country:
        type: string
      created:
        type: integer
      dedicated:
        type: boolean
      farmId:
        type: integer
      farmingPolicyId:
        type: integer
      gridVersion:
        type: integer
      id:
        type: string
      location:
        $ref: '#/definitions/types.Location'
      nodeId:
        type: integer
      publicConfig:
        $ref: '#/definitions/types.PublicConfig'
      rentContractId:
        type: integer
      rentedByTwinId:
        type: integer
      status:
        description: added node status field for up or down
        type: string
      total_resources:
        $ref: '#/definitions/types.Capacity'
      twinId:
        type: integer
      updatedAt:
        type: integer
      uptime:
        type: integer
      used_resources:
        $ref: '#/definitions/types.Capacity'
    type: object
  types.NodeWithNestedCapacity:
    properties:
      capacity:
        $ref: '#/definitions/types.CapacityResult'
      certificationType:
        type: string
      city:
        type: string
      country:
        type: string
      created:
        type: integer
      dedicated:
        type: boolean
      farmId:
        type: integer
      farmingPolicyId:
        type: integer
      gridVersion:
        type: integer
      id:
        type: string
      location:
        $ref: '#/definitions/types.Location'
      nodeId:
        type: integer
      publicConfig:
        $ref: '#/definitions/types.PublicConfig'
      rentContractId:
        type: integer
      rentedByTwinId:
        type: integer
      status:
        description: added node status field for up or down
        type: string
      twinId:
        type: integer
      updatedAt:
        type: integer
      uptime:
        type: integer
    type: object
  types.PublicConfig:
    properties:
      domain:
        type: string
      gw4:
        type: string
      gw6:
        type: string
      ipv4:
        type: string
      ipv6:
        type: string
    type: object
  types.PublicIP:
    properties:
      contractId:
        type: integer
      farmId:
        type: string
      gateway:
        type: string
      id:
        type: string
      ip:
        type: string
    type: object
  types.Twin:
    properties:
      accountId:
        type: string
      ip:
        type: string
      twinId:
        type: integer
    type: object
info:
  contact: {}
  description: grid proxy server has the main methods to list farms, nodes, node details
    in the grid.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Grid Proxy Server API
  version: "1.0"
paths:
  /contracts:
    get:
      consumes:
      - application/json
      description: Get all contracts on the grid, It has pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Max result per page
        in: query
        name: size
        type: integer
      - description: Set farms' count on headers based on filter
        in: query
        name: ret_count
        type: string
      - description: contract id
        in: query
        name: contract_id_id
        type: integer
      - description: twin id
        in: query
        name: twin_id
        type: integer
      - description: node id which contract is deployed on in case of ('rent' or 'node'
          contracts)
        in: query
        name: node_id
        type: integer
      - description: contract name in case of 'name' contracts
        in: query
        name: name
        type: string
      - description: contract type 'node', 'name', or 'rent'
        in: query
        name: type
        type: string
      - description: contract state 'Created', or 'Deleted'
        in: query
        name: state
        type: string
      - description: contract deployment data in case of 'node' contracts
        in: query
        name: deployment_data
        type: string
      - description: contract deployment hash in case of 'node' contracts
        in: query
        name: deployment_hash
        type: string
      - description: Min number of public ips in the 'node' contract
        in: query
        name: number_of_public_ips
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Contract'
            type: array
      summary: Show contracts on the grid
      tags:
      - GridProxy
  /farms:
    get:
      consumes:
      - application/json
      description: Get all farms on the grid, It has pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Max result per page
        in: query
        name: size
        type: integer
      - description: Set farms' count on headers based on filter
        in: query
        name: ret_count
        type: string
      - description: Min number of free ips in the farm
        in: query
        name: free_ips
        type: integer
      - description: Min number of total ips in the farm
        in: query
        name: total_ips
        type: integer
      - description: Pricing policy id
        in: query
        name: pricing_policy_id
        type: integer
      - description: farm version
        in: query
        name: version
        type: integer
      - description: farm id
        in: query
        name: farm_id
        type: integer
      - description: twin id associated with the farm
        in: query
        name: twin_id
        type: integer
      - description: farm name
        in: query
        name: name
        type: string
      - description: farm name contains
        in: query
        name: name_contains
        type: string
      - description: certificate type DIY or Certified
        in: query
        name: certification_type
        type: string
      - description: farm is dedicated
        in: query
        name: dedicated
        type: boolean
      - description: farm stellar_address
        in: query
        name: stellar_address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Farm'
            type: array
      summary: Show farms on the grid
      tags:
      - GridProxy
  /gateways:
    get:
      consumes:
      - application/json
      description: Get all nodes on the grid, It has pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Max result per page
        in: query
        name: size
        type: integer
      - description: Set nodes' count on headers based on filter
        in: query
        name: ret_count
        type: string
      - description: Min free reservable mru in bytes
        in: query
        name: free_mru
        type: integer
      - description: Min free reservable hru in bytes
        in: query
        name: free_hru
        type: integer
      - description: Min free reservable sru in bytes
        in: query
        name: free_sru
        type: integer
      - description: Min number of free ips in the farm of the node
        in: query
        name: free_ips
        type: integer
      - description: Node status filter, up/down.
        in: query
        name: status
        type: string
      - description: Node city filter
        in: query
        name: city
        type: string
      - description: Node country filter
        in: query
        name: country
        type: string
      - description: Get nodes for specific farm
        in: query
        name: farm_name
        type: string
      - description: Set to true to filter nodes with ipv4
        in: query
        name: ipv4
        type: string
      - description: Set to true to filter nodes with ipv6
        in: query
        name: ipv6
        type: string
      - description: Set to true to filter nodes with domain
        in: query
        name: domain
        type: string
      - description: Set to true to get the dedicated nodes only
        in: query
        name: dedicated
        type: boolean
      - description: Set to true to filter the available nodes for renting
        in: query
        name: rentable
        type: boolean
      - description: Set to true to filter rented nodes
        in: query
        name: rented
        type: boolean
      - description: rented by twin id
        in: query
        name: rented_by
        type: integer
      - description: available for twin id
        in: query
        name: available_for
        type: integer
      - description: List of farms separated by comma to fetch nodes from (e.g. '1,2,3')
        in: query
        name: farm_ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Node'
            type: array
      summary: Show nodes on the grid
      tags:
      - GridProxy
  /gateways/{node_id}:
    get:
      consumes:
      - application/json
      description: Get all details for specific node hardware, capacity, DMI, hypervisor
      parameters:
      - description: Node ID
        in: path
        name: node_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.NodeWithNestedCapacity'
      summary: Show the details for specific node
      tags:
      - GridProxy
  /nodes:
    get:
      consumes:
      - application/json
      description: Get all nodes on the grid, It has pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Max result per page
        in: query
        name: size
        type: integer
      - description: Set nodes' count on headers based on filter
        in: query
        name: ret_count
        type: string
      - description: Min free reservable mru in bytes
        in: query
        name: free_mru
        type: integer
      - description: Min free reservable hru in bytes
        in: query
        name: free_hru
        type: integer
      - description: Min free reservable sru in bytes
        in: query
        name: free_sru
        type: integer
      - description: Min number of free ips in the farm of the node
        in: query
        name: free_ips
        type: integer
      - description: Node status filter, up/down.
        in: query
        name: status
        type: string
      - description: Node city filter
        in: query
        name: city
        type: string
      - description: Node country filter
        in: query
        name: country
        type: string
      - description: Get nodes for specific farm
        in: query
        name: farm_name
        type: string
      - description: Set to true to filter nodes with ipv4
        in: query
        name: ipv4
        type: string
      - description: Set to true to filter nodes with ipv6
        in: query
        name: ipv6
        type: string
      - description: Set to true to filter nodes with domain
        in: query
        name: domain
        type: string
      - description: Set to true to get the dedicated nodes only
        in: query
        name: dedicated
        type: boolean
      - description: Set to true to filter the available nodes for renting
        in: query
        name: rentable
        type: boolean
      - description: Set to true to filter rented nodes
        in: query
        name: rented
        type: boolean
      - description: rented by twin id
        in: query
        name: rented_by
        type: integer
      - description: available for twin id
        in: query
        name: available_for
        type: integer
      - description: List of farms separated by comma to fetch nodes from (e.g. '1,2,3')
        in: query
        name: farm_ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Node'
            type: array
      summary: Show nodes on the grid
      tags:
      - GridProxy
  /nodes/{node_id}:
    get:
      consumes:
      - application/json
      description: Get all details for specific node hardware, capacity, DMI, hypervisor
      parameters:
      - description: Node ID
        in: path
        name: node_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.NodeWithNestedCapacity'
      summary: Show the details for specific node
      tags:
      - GridProxy
  /ping:
    get:
      consumes:
      - application/json
      description: ping the server to check if it running
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: ping the server
      tags:
      - ping
  /stats:
    get:
      consumes:
      - application/json
      description: Get statistics about the grid
      parameters:
      - description: Node status filter, up/down.
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Counters'
            type: array
      summary: Show stats about the grid
      tags:
      - GridProxy
  /twin/{twin_id}:
    post:
      consumes:
      - application/json
      description: submit the message
      parameters:
      - description: rmb.Message
        in: body
        name: msg
        required: true
        schema:
          $ref: '#/definitions/rmbproxy.Message'
      - description: twin id
        in: path
        name: twin_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rmbproxy.MessageIdentifier'
      summary: submit the message
      tags:
      - RMB
  /twin/{twin_id}/{retqueue}:
    get:
      consumes:
      - application/json
      description: Get the message result
      parameters:
      - description: twin id
        in: path
        name: twin_id
        required: true
        type: integer
      - description: message retqueue
        in: path
        name: retqueue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rmbproxy.Message'
            type: array
      summary: Get the message result
      tags:
      - RMB
  /twins:
    get:
      consumes:
      - application/json
      description: Get all twins on the grid, It has pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Max result per page
        in: query
        name: size
        type: integer
      - description: Set farms' count on headers based on filter
        in: query
        name: ret_count
        type: string
      - description: twin id
        in: query
        name: twin_id
        type: integer
      - description: account address
        in: query
        name: account_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Twin'
            type: array
      summary: Show twins on the grid
      tags:
      - GridProxy
swagger: "2.0"
