name: Go

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        export PATH=/home/runner/go/bin:$PATH
        go build cmds/proxy_server/main.go
      env:
        GO111MODULE: on

#     - name: Test
#       run: go test -v ./...

    