name: Go

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        export PATH=/home/runner/go/bin:$PATH
        export GIT_COMMIT=$(git rev-list -1 HEAD) 
        go build -ldflags "-X main.GitCommit=$GIT_COMMIT" cmds/proxy_server/main.go
      env:
        GO111MODULE: on

    - name: Code linter
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'

    - name: Test version
      run: ./main -v
