name: Schema test

on:
  workflow_dispatch:
    inputs:
      NETWORK:
        description: 'Network to run test on'
        required: true
        default: 'dev'
        type: string
  schedule:
    - cron: "0 6 * * *"


jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Installing all necessary packages
        run: pip install -r tests/schema_test/requirements.txt
      - name: Run tests
        run: NETWORK=${{ github.event.inputs.NETWORK }} python3 -m pytest -v ./tests/schema_test --html=report.html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: schema-pytest-results
          path: |
            report.html
            assets
        if: ${{ always() }}
